version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  node:
    build:
      context: ./node
    container_name: node-app
    volumes:
      - ./node/app:/usr/src/app
      - /usr/src/app/node_modules
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    depends_on: 
      - db
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    container_name: proxy
    ports:
      - "8080:8080"
    depends_on:
      - node
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
